smartGrowIoT/smartGrowIoT/urls.py
from django.urls import include
from django.urls import re_path
from django.contrib import admin

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path('', include('smart_grow.urls')),
    re_path('api/auth/', include('dj_rest_auth.urls')),
    re_path('api/auth/registration/', include('dj_rest_auth.registration.urls')),
]

smartGrowIoT/smart_grow/urls.py
from django.urls import path, include
from . import views
from .views import MySecureView, APIView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView


from django.contrib.auth import views as auth_views
from django.urls import re_path
from django.contrib import admin
#from .views import MyApiView


app_name = 'smart_grow'
urlpatterns = [
    path('', views.index, name='index'),
    path('devices/', views.devices_list, name='devices_list'), 
    path('device_info/', views.device_info, name='device_info'),
    path('kasa_devices_api/', views.kasa_devices, name='kasa_devices'),
    path('secure/', MySecureView.as_view(), name='secure'),
    path('login/', LoginView.as_view(template_name='smart_grow/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('climate-control-settings/', views.update_climate_control_settings, name='climate_control_settings'),
    #path('api/thresholds/', get_thresholds, name='get_thresholds'),
    path('api/store_device_info', views.store_device_info, name='store_device_info'),
    path('api/get_thresholds/', views.get_thresholds, name='get_thresholds'),
]   

smartGrowIoT/smart_grow/models.py
from django.db import models

class Sensor(models.Model):
    name = models.CharField(max_length=100)
    sensor_type = models.CharField(max_length=50)
    value = models.FloatField()
    last_updated = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name
    
class Device(models.Model):
    name = models.CharField(max_length=100)
    device_type = models.CharField(max_length=50)
    device_id = models.CharField(max_length=100, unique=True)
    is_online = models.BooleanField(default=False)
    battery_level = models.IntegerField(null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    device_location = models.CharField(max_length=255, default="Unknown")

    def __str__(self):
        return self.name

class KasaDevice(models.Model):
    name = models.CharField(max_length=100)
    kasa_device_id = models.CharField(max_length=100, unique=True)
    is_online = models.BooleanField(default=False)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
#not sure it wwe will nee this one 
class DeviceSensor(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)
    sensor = models.ForeignKey(Sensor, on_delete=models.CASCADE)
    last_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.device.name} - {self.sensor.name}"

class SensorData(models.Model):
    device_name = models.CharField(max_length=100, default="None")
    sensor = models.CharField(max_length=100, default="none")
    temperature = models.FloatField()
    humidity = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sensor.name} - {self.temperature} - {self.humidity} - {self.timestamp}"

class ClimateControlSettings(models.Model):
    temperature_threshold = models.FloatField()
    humidity_threshold = models.FloatField()
    device_1 = models.CharField(max_length=100)
    device_2 = models.CharField(max_length=100)

smartGrowIoT/smart_grow/forms.py
from django import forms
from .models import Device
from .models import ClimateControlSettings

class DeviceForm(forms.ModelForm):
    class Meta:
        model = Device
        fields = ['name', 'device_type', 'device_id', 'device_location']


class ClimateControlSettingsForm(forms.ModelForm):
    device_1 = forms.ChoiceField(choices=[])
    device_2 = forms.ChoiceField(choices=[])

    class Meta:
        model = ClimateControlSettings
        fields = ['temperature_threshold', 'humidity_threshold', 'device_1', 'device_2']
    
    def __init__(self, *args, device_info=None, **kwargs):
        super(ClimateControlSettingsForm, self).__init__(*args, **kwargs)
        if device_info:
            device_choices = [(device['alias'], device['alias']) for device in device_info]
            self.fields['device_1'].choices = device_choices
            self.fields['device_2'].choices = device_choices

smartGrowIoT/smart_grow/views.py
"""
Contents:
    • Index View
    • Device-related views
    • TP-Link Kasa device views
    • DRF authentication view
    • Climate Control functionality
"""

from datetime import datetime
import asyncio
import json
import os
import requests

# Standard library imports
from datetime import datetime
import asyncio
import json


# Third-party imports
from asgiref.sync import sync_to_async
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from rest_framework.response import Response
from rest_framework.authentication import TokenAuthentication
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.permissions import IsAuthenticated
from tplinkcloud import TPLinkDeviceManager
from firebase_admin import db

# Local imports
from .forms import ClimateControlSettingsForm
from .models import ClimateControlSettings, Device, SensorData
from .decorators import async_login_required

# ----------------------------
# Index view
# ----------------------------
@login_required
def index(request):
    return render(request, 'smart_grow/index.html')

# ----------------------------
# Device-related views
# ----------------------------
def devices_list(request):
    devices = Device.objects.all()
    context = {'devices': devices}
    return render(request, 'smart_grow/devices_list.html', context)

@login_required
def device_info(request):
    data = SensorData.objects.first()
    if data:
        context = {
                'device_name': data.device_name,
                'current_temperature': data.temperature,
                'current_humidity': data.humidity,
                'time_stamp' : data.timestamp
            }
    else:
        context = {
                'device_name': "None",
                'current_temperature': "none",
                'current_humidity': -1,
                'time_stamp' : -1
            }
    return render(request, 'smart_grow/device_info.html', context)
    
@api_view(['POST'])
def store_device_info(request):
    data = request.data
    device_name = data['device_name']
    temperature = data['temperaure']
    humidity = data['humidity']
    time_stamp = data['time_stamp']

    reading = SensorData(device_name=device_name, temperature=temperature, humidity=humidity, timestamp=time_stamp)
    reading.save()

    return Response({'status' : 'success'}, status=200)

# ----------------------------
# TP-Link Kasa device views
# ----------------------------
TPLINK_USERNAME = os.environ.get('TPLINK_USERNAME')
TPLINK_PASSWORD = os.environ.get('TPLINK_PASSWORD')

async def get_device_info(device):
    device_data = {
        "model_type": device.model_type.name,
        "alias": device.get_alias(),
        "device_info": json.loads(json.dumps(device.device_info, indent=2, default=lambda x: vars(x)
                        if hasattr(x, "__dict__") else x.name if hasattr(x, "name") else None)),
        "sys_info": json.loads(json.dumps(await device.get_sys_info(), indent=2, default=lambda x: vars(x)
                        if hasattr(x, "__dict__") else x.name if hasattr(x, "name") else None))
    }
    return device_data

async def get_tplink_cloud_devices(device_manager):
    devices = await device_manager.get_devices()
    tasks = [get_device_info(device) for device in devices]
    results = await asyncio.gather(*tasks)
    return results

def get_tplink_device_manager():
    return TPLinkDeviceManager(TPLINK_USERNAME, TPLINK_PASSWORD)

@async_login_required()
async def async_kasa_devices(request):
    device_manager = TPLinkDeviceManager(TPLINK_USERNAME, TPLINK_PASSWORD) 
    devices = await get_tplink_cloud_devices(device_manager)
    devices_to_ignore = ["UNKNOWN", "KP303", "KP303CHILD"]
    device_info = [{"alias": device.get('alias'), "device_model": device.get('model_type'), "relay_state": device.get('sys_info', {}).get('relay_state')} for device in devices if device.get('model_type') not in devices_to_ignore and device.get('sys_info') is not None]
    return device_info

@async_login_required()
async def kasa_devices(request):
    device_info = await async_kasa_devices(request)
    context = {"kasa_devices": device_info}
    return render(request, "smart_grow/kasa_devices_api.html", context)

# ----------------------------
# DRF authentication view
# ----------------------------
class MySecureView(APIView):
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    def get(self, request, format=None):
        content = {'message': 'Hello, authenticated user!'}
        return Response(content)

# ----------------------------
# Climate Control functionality
# ----------------------------
# @async_login_required()
async def update_climate_control_settings(request):
    
    settings = await sync_to_async(ClimateControlSettings.objects.first)()
    device_info = await async_kasa_devices(request)
    form = ClimateControlSettingsForm(request.POST or None, instance=settings, device_info=device_info)    
    print(device_info)
    success = False
    if form.is_valid():
        await sync_to_async(form.save)()
        await sync_to_async(post_thresholds)()
        success = True

    context = {'form': form, 'success': success}
    return render(request, 'smart_grow/climate_control_settings.html', context)

def post_thresholds():
    settings = ClimateControlSettings.objects.first()
    data = {
        'temperature' : {
            'temperature_threshold': settings.temperature_threshold,
            'device_1' : settings.device_1,
        },
        'humidity' : {
            'humidity_threshold': settings.humidity_threshold,
            'device_2' : settings.device_2
            }
    }
    # Set the trigger command in Firebase
    threshols_ref = db.reference("/thresholds")
    threshols_ref.set(data)

def get_thresholds(request):
    settings = ClimateControlSettings.objects.first()
    data = {
        'temperature_threshold': settings.temperature_threshold,
        'humidity_threshold': settings.humidity_threshold,
        'device_1' : settings.device_1,
        'device_2' : settings.device_2
    }
    return JsonResponse(data)

smartGrowIoT/smart_grow/templates/smart_grow/base.html
<!DOCTYPE html>
<html lang="en"> 
{% load static %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}hiiiiiiii{% endblock %}</title>
</head>
<body>
    {% block content %}{% endblock %}
</body>
</html>

smartGrowIoT/smart_grow/templates/smart_grow/climate_control_settings.html
{% extends 'smart_grow/base.html' %}

{% block content %}
  <h2>Climate Control Settings</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>

  {% if success %}
    <div class="alert alert-success mt-3" role="alert">
      Thresholds updated successfully.
    </div>
  {% endif %}
{% endblock %}

smartGrowIoT/smart_grow/templates/smart_grow/device_info.html
{% extends 'smart_grow/base.html' %}

{% block content %}
  <h1>Device Information</h1>
  {% if device_name %}
    <p>Device Name: {{ device_name }}</p>
    <p>Current Temperature: {{ current_temperature }}°C</p>
    <p>Current Humidity: {{ current_humidity }}%</p>
    <p>TimeStamp: {{ time_stamp }}</p>
  {% else %}
    <p>The device is not available.</p>
  {% endif %}
{% endblock %}

smartGrowIoT/smart_grow/templates/smart_grow/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Smart Grow</title>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  {% block content %}
    <h1>Welcome to Smart Grow</h1>
    <p>This is the home page for Smart Grow. Use the links below to navigate to different pages:</p>
    <ul>
      <li><a href="{% url 'smart_grow:kasa_devices' %}">Kasa Devices List</a></li>
      <li><a href="{% url 'smart_grow:device_info' %}">Device Information</a></li>
      <li><a href="{% url 'smart_grow:climate_control_settings' %}">Data Table</a></li>
    </ul>
  {% endblock %}
</body>
</html>

smartGrowIoT/smart_grow/templates/smart_grow/kasa_devices_api.html
{% extends 'smart_grow/base.html' %}

{% block content %}
  <h1>Kasa Devices List this is it </h1>
  <ul>
    {% for device in kasa_devices %}
      <li>
        <h2>{{ device.alias }}</h2>
        <p>Model: {{ device.device_model }}</p>
        <p>Is On: {{ device.relay_state }}</p>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

smartGrowIoT/smart_grow/templates/smart_grow/kasa_devices_list.html
{% extends 'smart_grow/base.html' %}

{% block content %}
  <h1>Kasa Devices List</h1>
  <ul>
    {% for device in kasa_devices %}
      <li>
        <h2>{{ device.device_info}}</h2>
        <p>Model: {{ device }}</p>
        <p>Is On: {{ device }}</p>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

smartGrowIoT/smart_grow/templates/smart_grow/login.html
{% extends 'smart_grow/base.html' %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

smartGrowIoT/smart_grow/templates/smart_grow/sensor_data_list.html
{% extends 'smart_grow/base.html' %}


{% block content %}
  <h1>Sensor Data</h1>
  <table border="1" cellpadding="10" cellspacing="0">
    <thead>
      <tr>
        <th>Temperature (°C)</th>
        <th>Humidity (%)</th>
        <th>Timestamp (CST)</th>
      </tr>
    </thead>
    <tbody>
     {% for temp, humidity, timestamp in zipped_data %}
        <tr>
            <td>{{ temp }}°C</td>
            <td>{{ humidity }}%</td>
            <td>{{ timestamp }}</td>
        </tr>
    {% endfor %}
    
    </tbody>
  </table>
{% endblock %}